// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SMJP.MasterDataServices.API.Data;

#nullable disable

namespace SMJP.MasterDataServices.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240521032727_SeedCompaniesToDb")]
    partial class SeedCompaniesToDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0-preview.3.24172.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SMJP.MasterDataServices.API.Models.Companies", b =>
                {
                    b.Property<int>("CompanyID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CompanyID"));

                    b.Property<string>("CompanyAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CompanyPhone")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Latitude")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogoUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Longitude")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProvinceID")
                        .HasColumnType("int");

                    b.HasKey("CompanyID");

                    b.ToTable("Companies");

                    b.HasData(
                        new
                        {
                            CompanyID = 1,
                            CompanyAddress = "Jl. M.H.Thamrin No.10",
                            CompanyEmail = "pertamina@example.com",
                            CompanyName = "Pertamina",
                            CompanyPhone = "1234567890",
                            CreatedBy = 1,
                            CreatedDate = new DateTime(2024, 5, 21, 3, 27, 27, 179, DateTimeKind.Utc).AddTicks(2882),
                            Latitude = "40.7128",
                            LogoUrl = "https://pertamina.com/logo1.png",
                            Longitude = "-74.0060",
                            ModifiedBy = 1,
                            ModifiedDate = new DateTime(2024, 5, 21, 3, 27, 27, 179, DateTimeKind.Utc).AddTicks(2885),
                            ProvinceID = 1
                        });
                });

            modelBuilder.Entity("SMJP.MasterDataServices.API.Models.Regions", b =>
                {
                    b.Property<int>("RegionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RegionID"));

                    b.Property<int>("CompanyID")
                        .HasColumnType("int");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("RegionLatitude")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("RegionLongitude")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("RegionName")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("RegionID");

                    b.HasIndex("CompanyID");

                    b.ToTable("Regions");

                    b.HasData(
                        new
                        {
                            RegionID = 1,
                            CompanyID = 1,
                            CreatedBy = 1,
                            CreatedDate = new DateTime(2024, 5, 21, 3, 27, 27, 179, DateTimeKind.Utc).AddTicks(3010),
                            ModifiedBy = 1,
                            ModifiedDate = new DateTime(2024, 5, 21, 3, 27, 27, 179, DateTimeKind.Utc).AddTicks(3011),
                            RegionLatitude = "40.7128",
                            RegionLongitude = "-74.0060",
                            RegionName = "Jakarta Pusat"
                        });
                });

            modelBuilder.Entity("SMJP.MasterDataServices.API.Models.Schedules", b =>
                {
                    b.Property<int>("ScheduleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ScheduleID"));

                    b.Property<int>("CompanyID")
                        .HasColumnType("int");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("RegionID")
                        .HasColumnType("int");

                    b.Property<int>("ShiftID")
                        .HasColumnType("int");

                    b.Property<int>("SiteID")
                        .HasColumnType("int");

                    b.HasKey("ScheduleID");

                    b.HasIndex("CompanyID");

                    b.HasIndex("RegionID");

                    b.HasIndex("SiteID");

                    b.ToTable("Schedules");

                    b.HasData(
                        new
                        {
                            ScheduleID = 1,
                            CompanyID = 1,
                            CreatedBy = 1,
                            CreatedDate = new DateTime(2024, 5, 21, 10, 27, 27, 179, DateTimeKind.Local).AddTicks(3138),
                            Date = new DateTime(2024, 5, 21, 10, 27, 27, 179, DateTimeKind.Local).AddTicks(3126),
                            ModifiedBy = 1,
                            ModifiedDate = new DateTime(2024, 5, 21, 10, 27, 27, 179, DateTimeKind.Local).AddTicks(3139),
                            RegionID = 1,
                            ShiftID = 1,
                            SiteID = 1
                        });
                });

            modelBuilder.Entity("SMJP.MasterDataServices.API.Models.Shifts", b =>
                {
                    b.Property<int>("ShiftID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ShiftID"));

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EndAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("ShiftID");

                    b.ToTable("Shifts");

                    b.HasData(
                        new
                        {
                            ShiftID = 1,
                            CreatedBy = 1,
                            CreatedDate = new DateTime(2024, 5, 21, 3, 27, 27, 179, DateTimeKind.Utc).AddTicks(3252),
                            EndAt = new DateTime(2024, 5, 21, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedBy = 1,
                            ModifiedDate = new DateTime(2024, 5, 21, 3, 27, 27, 179, DateTimeKind.Utc).AddTicks(3252),
                            StartAt = new DateTime(2024, 5, 21, 7, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Morning"
                        });
                });

            modelBuilder.Entity("SMJP.MasterDataServices.API.Models.Sites", b =>
                {
                    b.Property<int>("SiteID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SiteID"));

                    b.Property<int>("CompanyID")
                        .HasColumnType("int");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("RegionID")
                        .HasColumnType("int");

                    b.Property<string>("SiteDesc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SiteLatitude")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SiteLongitude")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SiteName")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("SiteID");

                    b.HasIndex("CompanyID");

                    b.HasIndex("RegionID");

                    b.ToTable("Sites");

                    b.HasData(
                        new
                        {
                            SiteID = 1,
                            CompanyID = 1,
                            CreatedBy = 1,
                            CreatedDate = new DateTime(2024, 5, 21, 3, 27, 27, 179, DateTimeKind.Utc).AddTicks(3042),
                            ModifiedBy = 1,
                            ModifiedDate = new DateTime(2024, 5, 21, 3, 27, 27, 179, DateTimeKind.Utc).AddTicks(3043),
                            RegionID = 1,
                            SiteDesc = "Description of Pertamina Site",
                            SiteLatitude = "48.8584",
                            SiteLongitude = "2.2945",
                            SiteName = "Pertamina Training & Consulting"
                        });
                });

            modelBuilder.Entity("SMJP.MasterDataServices.API.Models.Regions", b =>
                {
                    b.HasOne("SMJP.MasterDataServices.API.Models.Companies", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("SMJP.MasterDataServices.API.Models.Schedules", b =>
                {
                    b.HasOne("SMJP.MasterDataServices.API.Models.Companies", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SMJP.MasterDataServices.API.Models.Regions", "Region")
                        .WithMany()
                        .HasForeignKey("RegionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SMJP.MasterDataServices.API.Models.Sites", "Site")
                        .WithMany()
                        .HasForeignKey("SiteID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("Region");

                    b.Navigation("Site");
                });

            modelBuilder.Entity("SMJP.MasterDataServices.API.Models.Sites", b =>
                {
                    b.HasOne("SMJP.MasterDataServices.API.Models.Companies", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SMJP.MasterDataServices.API.Models.Regions", "Region")
                        .WithMany()
                        .HasForeignKey("RegionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("Region");
                });
#pragma warning restore 612, 618
        }
    }
}
